<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: gradido/GradidoTransaction.proto

namespace GPBMetadata\Gradido;

class GradidoTransaction
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \GPBMetadata\Gradido\BasicTypes::initOnce();
        $pool->internalAddGeneratedFile(
            '
‘
 gradido/GradidoTransaction.protoproto.gradido"V
GradidoTransaction,
sig_map (2.proto.gradido.SignatureMap

body_bytes (bproto3'
        , true);

        static::$is_initialized = true;
    }
}

